gui:
  nerdFontsVersion: "3"
git:
  pagers:
    - pager: delta --dark --paging=never
customCommands:
  - key: 'D'
    description: "View structural diff (Difftastic)"
    context: files
    command: 'difft --color=always --display=side-by-side-show-both "{{.SelectedFile.Name}}"'
    output: terminal
  - key: 'D'
    description: "View commit diff (Difftastic)"
    context: commits
    command: 'git dft {{.SelectedLocalCommit.Sha}}~1 {{.SelectedLocalCommit.Sha}}'
    output: terminal
