gui:
  nerdFontsVersion: "3"

git:
  paging:
    pager: delta --dark --paging=never

customCommands:
  - key: 'D'
    description: "View structural diff (Difftastic)"
    context: files
    command: 'difft --color=always --display=side-by-side-show-both "{{.SelectedFile.Name}}"'
    subprocess: true
  - key: 'D'
    description: "View commit diff (Difftastic)"
    context: localCommits
    command: 'git dft {{.SelectedLocalCommit.Sha}}~1 {{.SelectedLocalCommit.Sha}}'
    subprocess: true
